name: PodcrashAPI
main: com.podcrash.api.plugin.PodcrashSpigot
version: 1.0
author: RainDance

softdepend: [SlimeWorldManager, ProtocolLib]

commands:
  addrole:
    description: Add a new role to the game.
    usage: /addrole <Role Name> <Color> <Position>
  setrole:
    description: Set a players role or take it away.
    usage: /setrole <Role> <PlayerName>
  bal:
    description: Check how much gold you currently have.
    usage: /bal
  buy:
    description: Purchase a new item with your gold.
    usage: /buy <Name of Item>
  confirm:
    description: Confirm the purchase of an item.
    usage: /confirm <Name of Item>
  pworld:
    description: use slime world