file:
  path: slime_worlds # The path to the directory where slime worlds are stored
mysql:
  enabled: true
  host: 127.0.0.1
  port: 3306
  username: my_mysql_username
  password: my_mysql_password
  database: slimeworldmanager
mongodb:
  enabled: true
  host: 127.0.0.1
  port: 27017
  username: my_mongo_username
  password: my_mongo_password
  auth: admin
  database: worldmaps
  collection: mapdata